# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    
    vb.gui = with_gui
    if with_gui
      vb.cpus = 4
      vb.memory = 4096
      vb.customize ["modifyvm", :id, "--vram", "128"]
    end
  end
  
  if ENV.has_key?("WORKSPACE")
    config.vm.provision "shell", run: "always", inline: "echo 'Linking workspace: ~vagrant/workspace -> #{ENV["WORKSPACE"]}'"
    config.vm.synced_folder ENV["WORKSPACE"], "C:/Users/vagrant/workspace",
        id: "workspace-root",
        :nfs => true,
        :mount_options => ['nolock','vers=3','tcp','noatime','actimeo=1','resvport']
  end

end

