# -*- mode: ruby -*-
# vi: set ft=ruby :

# The MIT License (MIT)
# 
# Copyright (c) 2016 Kevin Brightwell
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This vagrantfile is used for creating a ubuntu trusty environment for 
# building the procsim project

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/wily64"
  config.env.enable

  with_gui = ENV.has_key?("WITH_GUI") ? ENV["WITH_GUI"] : false
  
  cpu_count = ENV.has_key?("CPUS") ? ENV["CPUS"] : (with_gui ? 4 : 2)
  memory_count = ENV.has_key?("MEMORY") ? ENV["MEMORY"] :  (with_gui ? 4096 : 2048)

  config.vm.provision "shell", run: "always", inline: "echo 'Provisioning: workspace=#{WORKSPACE} CPUS=#{cpu_count} MEMORY=#{memory_count}'"

  config.vm.provider "virtualbox" do |vb|    
    # This fixes problems with the log file created
    vb.customize ["modifyvm", :id, "--uartmode1", "file", "procsim-xenial.log" ]

    vb.cpus = cpu_count
    vb.memory = memory_count

    vb.gui = with_gui
    if with_gui
      vb.customize ["modifyvm", :id, "--vram", "128"]
    end
  end

  if ENV.has_key?("WORKSPACE")
    WORKSPACE = ENV["WORKSPACE"]
    config.vm.provision "shell", run: "always", inline: "echo 'Linking workspace: ~/workspace -> #{WORKSPACE}'"
    
    config.vm.synced_folder ENV["WORKSPACE"], "/home/vagrant/workspace"
  end

  if with_gui
    config.vm.provision "shell", privileged: true, inline: <<-EOF 
      apt-get install -y --no-install-recommends ubuntu-desktop 
      apt-get install -y gnome-terminal \
                        qt56creator \
                        clang-format \ # We will likely need to see generated files
                        unity-lens-applications \
                        unity-lens-files
    EOF
  end

  # Clean-up dead packages, no need to keep them
  config.vm.provision "shell", privileged: true, inline: <<-EOF
    echo "Cleaning unneeded packages"
    apt-get autoremove --purge -y
  EOF
end # end vagrant file 
