# -*- mode: ruby -*-
# vi: set ft=ruby :

# The MIT License (MIT)
# 
# Copyright (c) 2016 Kevin Brightwell
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# This vagrantfile is used for creating a Mac OS X El Capitain environment for 
# building the procsim project

Vagrant.configure("2") do |config|
    with_gui = ENV.has_key?("WITH_GUI") ? ENV["WITH_GUI"] : false

    config.vm.provider "virtualbox" do |vb|    
        vb.gui = with_gui
        if with_gui
            vb.cpus = 4
            vb.memory = 4096
            vb.gui = true
            vb.customize ["modifyvm", :id, "--vram", "128"]
        end
    end

    # Disable the default synced folder, it's not supported on 'darwin' yet
    config.vm.synced_folder ".", "/vagrant", disabled: true

    if ENV.has_key?("WORKSPACE")
        config.vm.provision "shell", run: "always", inline: "echo 'Linking workspace: ~vagrant/workspace -> #{ENV["WORKSPACE"]}'"

        config.vm.network "private_network", ip: "10.10.10.10"
        config.vm.synced_folder ENV["WORKSPACE"], "/Users/vagrant/workspace",
            id: "workspace-root",
            :nfs => true,
            :mount_options => ['nolock','vers=3','tcp','noatime','actimeo=1','resvport']
    end
 
end